# Generated by Django 5.1.5 on 2025-01-23 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvecCarlingage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'avec_carlingage',
            },
        ),
        migrations.CreateModel(
            name='AvecPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'avec_plots',
            },
        ),
        migrations.CreateModel(
            name='DegreChoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'degre_choc',
            },
        ),
        migrations.CreateModel(
            name='FacteurChoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'facteur_choc',
            },
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvrage', models.CharField(max_length=25, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('schema_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('code_client', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='media/core/img')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ouvrages',
            },
        ),
        migrations.CreateModel(
            name='OwnerCodeProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieledorder', models.IntegerField(unique=True)),
                ('fieldtype', models.IntegerField()),
                ('fieldvalue', models.CharField(max_length=50)),
                ('fieldlabel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'owner_code_properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyConsolidationParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('source_priority', models.CharField(max_length=150, null=True)),
                ('display_mode', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'property_consolidation_param ',
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=75, unique=True)),
                ('source', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(max_length=75, null=True)),
                ('description', models.CharField(max_length=254, null=True)),
                ('trade', models.CharField(max_length=100, null=True)),
                ('function', models.CharField(max_length=50, null=True)),
                ('lot', models.CharField(max_length=50, null=True)),
                ('room', models.CharField(max_length=50, null=True)),
                ('code_client_ouvrage', models.CharField(max_length=75, null=True)),
                ('code_fournisseur', models.CharField(max_length=50, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, null=True)),
                ('date_last_modified_dc', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('avec_carlingage', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.aveccarlingage')),
                ('avec_plots', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.avecplot')),
                ('degre_choc', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.degrechoc')),
                ('facteur_choc', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.facteurchoc')),
            ],
            options={
                'db_table': 'consolidated_objects',
            },
        ),
        migrations.CreateModel(
            name='ObjectsFromCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=75, unique=True)),
                ('source', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(max_length=75, null=True)),
                ('description', models.CharField(max_length=254, null=True)),
                ('trade', models.CharField(max_length=100, null=True)),
                ('function', models.CharField(max_length=50, null=True)),
                ('lot', models.CharField(max_length=50, null=True)),
                ('room', models.CharField(max_length=50, null=True)),
                ('code_client_object', models.CharField(max_length=75, null=True)),
                ('code_fournisseur', models.CharField(max_length=50, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('date_last_modified', models.DateTimeField(blank=True, null=True)),
                ('date_last_modified_dc', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('avec_carlingage', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.aveccarlingage')),
                ('avec_plots', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.avecplot')),
                ('degre_choc', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.degrechoc')),
                ('facteur_choc', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.facteurchoc')),
            ],
            options={
                'db_table': 'objects_from_cao',
            },
        ),
        migrations.CreateModel(
            name='OwnerCodeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldorder', models.IntegerField(unique=True)),
                ('fieldvalue', models.CharField(max_length=50)),
                ('objconso_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.consolidatedobjects')),
            ],
            options={
                'db_table': 'owner_code_details',
            },
        ),
    ]
