# Generated by Django 5.1.5 on 2025-01-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='schema_name',
            field=models.CharField(max_length=10),
        ),
    ]
