# Generated by Django 5.1.5 on 2025-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ouvrage_schema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
