# Generated by Django 5.1.5 on 2025-01-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_consolidatedobjects_code_client_ouvrage_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertyconsolidationparam',
            table='property_consolidation_param',
        ),
    ]
