# Generated by Django 5.1.5 on 2025-01-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_propertyconsolidationparam_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consolidatedobjects',
            old_name='code_client_ouvrage',
            new_name='code_client_object',
        ),
    ]
