# Generated by Django 5.1.5 on 2025-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_code_client_ouvrage_consolidatedobjects_code_client_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degrechoc',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='schema_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
