# Generated by Django 5.1.5 on 2025-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_degrechoc_value_alter_ouvrage_schema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyconsolidationparam',
            name='property_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
