# Generated by Django 5.1.5 on 2025-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_propertyconsolidationparam_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedobjects',
            name='date_traitement_cao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectsfromcao',
            name='date_traitement_cao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
