# Generated by Django 5.1.5 on 2025-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_consolidatedobjects_date_traitement_cao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCodeLov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'owner_coode_lov',
            },
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='schema_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
