# Generated by Django 5.1.5 on 2025-01-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ownercodelov_alter_ouvrage_schema_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ownercodelov',
            table='owner_code_lov',
        ),
    ]
