# Generated by Django 5.1.5 on 2025-01-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ownercodelov_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownercodeproperties',
            old_name='fieledorder',
            new_name='fieldorder',
        ),
    ]
