# Generated by Django 5.1.5 on 2025-01-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_fieledorder_ownercodeproperties_fieldorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidatedobjects',
            name='uid',
        ),
    ]
