# Generated by Django 5.1.5 on 2025-01-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_consolidatedobjects_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownercodedetails',
            name='fieldorder',
        ),
        migrations.RemoveField(
            model_name='ownercodedetails',
            name='objconso_id',
        ),
        migrations.AddField(
            model_name='ownercodedetails',
            name='objconso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.consolidatedobjects'),
        ),
        migrations.AddField(
            model_name='ownercodedetails',
            name='ownercode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ownercodeproperties'),
        ),
        migrations.AlterField(
            model_name='ownercodedetails',
            name='fieldvalue',
            field=models.CharField(max_length=150),
        ),
    ]
