# Generated by Django 5.1.5 on 2025-02-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_ownercodedetails_fieldorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercodelov',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
