# Generated by Django 5.1.5 on 2025-02-12 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0016_ownercodelov_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuvrageAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ad', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ouvrage_ad',
            },
        ),
        migrations.CreateModel(
            name='OuvrageGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#42f56c', 'Vert'), ('#FFA500', 'Orange'), ('#FFFF00', 'Jaune')], default='#C70039', max_length=20)),
                ('droit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ouvragead')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ouvrage')),
            ],
            options={
                'db_table': 'ouvrage_groupe',
                'unique_together': {('ouvrage', 'groupe')},
            },
        ),
    ]
