# Generated by Django 5.1.5 on 2025-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ouvragead_ouvragegroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercodedetails',
            name='fieldorder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
