# Generated by Django 5.1.5 on 2025-02-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ownercodedetails_fieldorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyconsolidationparam',
            name='position_index',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
