version: '3.3'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: gunicorn --timeout 600 double_codification.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - logs:/app/logs
    env_file:
      - .env
    expose:
      - 8000 
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "5856:80"
    depends_on:
      - web
    networks:
      - app_network
volumes:
  static_volume:
  logs:

networks:
  app_network:
    driver: bridge